# Generated by Django 4.2.6 on 2023-10-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=20, unique=True, verbose_name='ISBN'),
        ),
    ]
