# Generated by Django 4.2.6 on 2023-10-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_book_genre_en_book_genre_ru_book_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='book',
            name='author_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image_en',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image_ru',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='book',
            name='language_en',
            field=models.CharField(max_length=20, null=True, verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='book',
            name='language_ru',
            field=models.CharField(max_length=20, null=True, verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='book',
            name='page_count_en',
            field=models.PositiveIntegerField(null=True, verbose_name='Количество страниц'),
        ),
        migrations.AddField(
            model_name='book',
            name='page_count_ru',
            field=models.PositiveIntegerField(null=True, verbose_name='Количество страниц'),
        ),
        migrations.AddField(
            model_name='book',
            name='publication_date_en',
            field=models.DateField(null=True, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='book',
            name='publication_date_ru',
            field=models.DateField(null=True, verbose_name='Дата публикации'),
        ),
    ]
