# Generated by Django 4.2.6 on 2023-10-23 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_book_author_en_book_author_ru_book_cover_image_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_image_en',
        ),
        migrations.RemoveField(
            model_name='book',
            name='cover_image_ru',
        ),
        migrations.RemoveField(
            model_name='book',
            name='page_count_en',
        ),
        migrations.RemoveField(
            model_name='book',
            name='page_count_ru',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publication_date_en',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publication_date_ru',
        ),
    ]
